spring:
  application:
    name: 51-Greys-API
    
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
#    url: jdbc:mysql://localhost:3306/51_greys_employee_management_database
#    username: root
#    password: root
    url:  jdbc:mysql://51-greys-test-database.mysql.database.azure.com/testdb
    username: greysdb
    password: Mother1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# Will be used once we implement security features
  security:
    user:
      name: itsme
      password: password  
  
server:
  port: 8080
  
sp-login:
  username: spadmin
  password: admin
  
sp-url: http://172.174.175.230:8080/identityiq/scim/v2